### PR TITLE
Added 2018 rentstab data to nycdb

### PR DESCRIPTION
**Pull request by sraby**
This PR addresses issue #121 by adding @toolness's 2018 rent stab data as it's own table in nycdb. Incorporating folks' comments on the issue thread, I generated the schema with 4 columns: 

```
Year: integer
Bbl: char(10)
SoaRentstabUnits: integer
PdfOfSoa: text
```

image

Other than the schema, each other piece of this PR follows our general protocol for past table additions.

### CODE REVIEW

**Comment by sraby** [comment]
@toolness @aepyornis @lblok @austensen, let me know if you have any thoughts about this re: our conversation in the #121 thread!

**Comment by austensen** [comment]
This looks good to me! My only question is about the name of the table. Given that you have the year column, I was thinking that in future years new data could just be added to the same table so that we don't need to have `rentstab_18`, `rentstab_19`, ...
I don't know much about the `doffer` process for creating the data, so maybe that doesn't make sense, but I thought that might be an easier way to organize the data in NYCDB. What do you think?

**Comment by sraby** [comment]
Good point @austensen! I'm open to calling it something like `rentstab_v2` or something, but I know that there are some concerns around the potential for the schema to change year to year. Like, for example, we may be able to grab other fields next year like Net Operating Income, which may be confusing if added to a combined table when some years may not have any data to populate that field. 

I think there are pros and cons to either approach though, so happy to hear more thoughts about it.

**Comment by austensen** [comment]
ah okay that makes sense then. I agree that both ways work and I don't have a preference either way.

If all the PDFs are already archived, then in the future if we want to extract additional fields couldn't we go back and pull those out for previous years as well to keep everything consistent? The harder part is getting the PDFs rather than extracting things from them, right? Or are you thinking of a case where we get new/different PDFs in later years?

**Comment by sraby** [comment]
yes exactly @austensen! My understanding is that because @toolness has archived all of the pdfs of SOAs he scraped, we can always return to the archive if we want to scrape extra fields. However, as you said, I think the worry stems more from if/when we are able to scrape different pdfs from DOF (like NOPVs), which then we wouldn't have an archive ready to go.

Perhaps what we could do, though, is have one table for *each type of PDF* that we end up scraping. So, this table could be specifically for SOAs, and if we end up grabbing NOPVs, that could live in another table. Therefore, we'd only need to create a new table when we do get access to new DOF files, and could update each one in place yearly. Any thoughts on that?

**Comment by austensen** [comment]
Thanks, that makes perfect sense. yeah, I like that idea of organizing by type of pdf.

**Comment by sraby** [comment]
Oh cool! Ok, so maybe we can name this table as `rentstab_soa` to signify that it's rentstab-related data that we can find specifically on SOAs? What do others think @toolness @lblok @aepyornis ?

**Comment by lblok** [comment]
I'm not entirely following

**Comment by sraby** [comment]
Really good point @lblok! Your comment made me rethink things, and since most people will be joining this table with the older rentstab table for comparisons, it makes a lot of sense to prioritize continuity in the field names. That way, too, we wouldn't have to include a `year` field and then every year's separate unit count would be clearly understandable— sort of solving for most of the issued you all brought up in this thread.

In my opinion, the clearest name for this new table would then be `rentstab_v2` as it would indicate it as a continuation of the previous rentsab work. It would then include this schema:

```
Bbl: char(10)
uc2018: integer
soapdf2018: text
``` 

I've been discussing with @toolness and I think he has some ideas too on how to optimize the generation of this over the next few years. 

What do people think?

**Comment by lblok** [comment]
Sounds good to me!

**Comment by sraby** [comment]
@austensen @aepyornis any more thoughts on this before we move forward?

**Comment by austensen** [comment]
This new approach makes a lot of sense. No other thoughts from me before merging it in. thanks!

**Comment by sraby** [comment]
Thanks for the feedback everyone! Will merge this later today :)

**Pull request merged**
