### PR TITLE
Add the Property Address Directory

### LINKED ISSUE #77: Add NYC Property Address Directory (PAD) as a dataset
The [NYC open data feed for PAD](https://data.cityofnewyork.us/City-Government/Property-Address-Directory/bc8t-ecyu) is useful because it essentially maps BINs to BBLs, which is very useful for cross-referencing different kinds of datasets.

It will also be useful in Who Owns What, so that we can let users know that the statistics they're seeing for a building might actually represent aggregate data amongst multiple buildings (e.g. if multiple BINs map to the same BBL).

### PR DESCRIPTION
**Pull request by toolness**
Fixes #77.

### CODE REVIEW

**Comment by toolness** [comment]
Okay, so this doesn't add the _entire_ PAD, because the ZIP file that comes with the [download](https://data.cityofnewyork.us/City-Government/Property-Address-Directory/bc8t-ecyu) has three different CSVs in it.  This PR only brings in `bobaadr.txt`, a.k.a. the **ADR Table**, which I think is the main one we need that maps BBLs to BINs.  The other one, the BBL table, seems largely useful for condos, but I'm also very new to all this so I'm not sure if we need it.

**Comment by toolness** [comment]
Ok, so Travis is failing because PyProj seems to have changed the way it transforms coordinates.  I've resolved this in #103 so if/when we merge that and then rebase this PR, the tests should pass again.

**Comment by toolness** [comment]
Ok I think this is good to go, thanks to #104.  @sraby can you verify that this new PAD dataset contains the data you need?

**Comment by sraby** [comment]
@toolness, yep! The `bobaddr.txt` table is the one I've been using. Not sure if the fields other than bin and bbl will be useful to anyone, but I guess it doesn't hurt to include them. I think you can go ahead and merge it.

Oh, and thanks for making an index on bin and bbl— important :)

**Comment by aepyornis** [comment]
condo numbers could be useful, but it can always be added later if someone needs it.

**Comment by toolness** [comment]
Ok just added it to `verify.py`!  There are currently 1,313,032 rows in the dataset so I figured 1,000,000 was a decent verify number.

Will rebase when I merge this PR for sure.

**Comment by aepyornis** [comment]
one other thing. sorry about this!

since the dataset contains three csvs, i think this table should be named nothing other than **pad**. It might be future-proofing, but it would be annoying to have to change the table name later if someone wanted to import the other tables in the dataset. perhaps **pad_adr**?

**Comment by toolness** [comment]
Ah good idea, just renamed the `pad` table to `pad_adr`!

**Comment by sraby** [comment]
good catch @aepyornis! Ok, by me, this is ready to merge :)

**Pull request merged**
