### PR TITLE
add mci applications data

### PR DESCRIPTION
**Pull request by wshenyc**
MCI application for Jan 2010 to Nov 2020

### CODE REVIEW

**Comment by aepyornis** [comment]
Hi @wshenyc. Thanks for the submission! I think if you replace the dash with an underscore in this filename:  `mci-applications.yml` the tests will pass again and the dataset name will be consistent.

**Comment by austensen** [comment]
This one has yet another different date format with 2-digit years (`12/31/22`), so we needed more changes to the date parser. I wasn't sure what to use for the threshold when guessing 19XX or 20XX, but settled on 40 pretty arbitrarily. Let me know if anyone has a better idea for how to handle this.

**Comment by steve52** [comment]
> This one has yet another different date format with 2-digit years (12/31/22), so we needed more changes to the date parser. I wasn't sure what to use for the threshold when guessing 19XX or 20XX, but settled on 40 pretty arbitrarily. Let me know if anyone has a better idea for how to handle this.

Yikes! Why would anyone use 2 digit years in 2023!!! 🤦  I don't know enough about the data that gets pulled into nycdb to say if 40 is "safe" or not, but it _feels_ safe to me... 🤷 . I take it we can't be sure of the earliest possible date or latest possible date we'd ever see?

I do recommend adding a comment though next to where you're using the '40' in order to let future people who edit that code why that value was chosen and what it's significance is. Just a suggestion though.

**Comment by steve52** [comment]
FYI, tested locally and this PR seems to work as expected for me! I think it looks good.

**Review by steve52 — APPROVED** [review]

**Comment by austensen** [comment]
Thanks for reviewing, and good point for making the 1900/2000 cutoff more clear/documented - just added that.

**Review by austensen — APPROVED** [review]

**Pull request merged**
