### PR TITLE
add support for iso8601 dates in typecast

### LINKED ISSUE #117: Allow ISO8601 dates
Currently the `date()` function from the `Typecast` class doesn't support ISO8601 dates (`2019-12-01`).

### PR DESCRIPTION
**Pull request by austensen**
The new OCA data I'm working on uses this format and I saw the "TODO" note that more date formats should be accepted, so thought I would add this. fixes #117

### CODE REVIEW

**Comment by toolness** [comment]
Oh nice, this is great, thanks!  I think the code looks good, and thanks for adding the tests too.

I am going to give a day or two for others to review this if they want, and if no one has any objections then I will merge it.

**Comment by austensen** [comment]
Sounds good. And just let me know if you think I should add any other formats like that. 

By the way, would it be easy for you to incorporate this into your branch for the plugins PR? For the OCA data I'm still depending on that branch and have dates in this format that aren't being parsed properly.

**Comment by toolness** [comment]
Oh yeah sure!  As soon as this merges into `master`, I will merge `master` into the plugins branch (#107) so it's up to date.

**Comment by aepyornis** [comment]
thanks -- looks great!

**Comment by aepyornis** [comment]
> By the way, would it be easy for you to incorporate this into your branch for the plugins PR? For the OCA data I'm still depending on that branch and have dates in this format > that aren't being parsed properly.

@austensen @toolness This is probably not the best place for this conversation but can you remind me again why the OCA data depends on the plugins branch instead of being included directly into NYCDB?

**Comment by toolness** [comment]
> @austensen @toolness This is probably not the best place for this conversation but can you remind me again why the OCA data depends on the plugins branch instead of being included directly into NYCDB?

This goes back to the fundamental reason for the plugins system outlined in https://github.com/nycdb/nycdb/pull/107 -- we want to be able to add _experimental_ datasets without needing to fork NYCDB.  Currently the OCA dataset is in an experimental stage because we don't actually know what the ideal NYCDB dataset will look like, but as that picture solidifies (through the development and use of the experimental plugin), we will be able to get a better idea of it, and eventually propose it as a PR directly into to NYCDB.

**Comment by aepyornis** [comment]
> > @austensen @toolness This is probably not the best place for this conversation but can you remind me again why the OCA data depends on the plugins branch instead of being included directly into NYCDB?
> 
> This goes back to one of the fundamental reasons for the plugins system outlined in #107 -- we want to be able to add _experimental_ datasets without needing to fork NYCDB. Currently the OCA dataset is in an experimental stage because we don't actually know what the ideal NYCDB dataset will look like, but as that picture solidifies (through the development and use of the experimental plugin), we will be able to get a better idea of it, and eventually propose it as a PR directly into to NYCDB.

Gotcha. Personally, I will probably find it easier to keep experiments and works-in-progress as a separate git branch rather than having to deal with the infrastructure of a plugin system. But if it helps with a development problem you two are having that can't be easily solved with git, let's continue to refine the plugin proposal!

**Pull request merged**
