### PR TITLE
Add GIST index on an st_point of pluto_latest lat/long

### PR DESCRIPTION
**Pull request by kfinn**
I've been messing around more with a good cause eviction map, and I think this index is important too. I have a demo that's looking great on my local copy of nycdb with this index added, I think I can test it out on a hosted environment once we add this GIST index!

### CODE REVIEW

**Comment by kfinn** [comment]
I'm wondering if maybe I should set an `SRID` on the point in the index? I can tell my prototype has a kind of skewed hexagonal grid, which I bet is related to me not using any kind of spacial reference system.

**Comment by austensen** [comment]
This looks good - and yeah I think adding SRID makes sense.
Previously I had tried to just add a point geom column to the table, but was running into some problems with AddGeometryColumn and [removed it recently](https://github.com/nycdb/nycdb/pull/347/files), but would be nice to just have this available all the time. When first adding PostGIS and all the [boundaries files](https://github.com/nycdb/nycdb/pull/321) we had talked about keeping all the spatial columns in the same SRID (2263, which is used by most agencies and is in feet so good for spatial calculations compared to degrees), so that's what I had here before removing. But I think having a lat/long (srid=4326) version like this also makes sense for pluto since that's what's  needed for geojson and web mapping generally. Later on I'll try to work out whatever the problem was and add the column back in addition to the index.

**Comment by kfinn** [comment]
@austensen I added the SRID!

**Comment by kfinn** [comment]
I just reread the previous comment and redid my work to not only add an index but also a `latitudelongitudegeom` column. Let me know if I got it right or if you have thoughts on naming/SRID/etc

**Review by austensen — APPROVED** [review]

**Pull request merged**
